git:
  branch: master

wants:
  mongo: true

secrets:
  - SECRET
  - GROUND_TRUTH_ID
  - GROUND_TRUTH_SECRET
  - GRAPHQL_AUTH
  - ADMIN_SECRET
  - DAILY_KEY

health:
  path: /status

env:
  GROUND_TRUTH_URL: https://login.hack.gt
  GRAPHQL_URL: https://registration.2021.hack.gt/graphql
  PRODUCTION: true
  PORT: 3000
  CMS_URL: https://cms.hack.gt/admin/api
  
